[package]
name = "privacy-engine"
version = "0.1.0"
edition = "2024"

[dependencies]
aes-gcm = "0.10.3"
hkdf = "0.12.4"
rand = "0.9.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.140"
x25519-dalek = "2.0.1"
hex = "0.4"

